version: 0.6.4.{build}-{branch}
configuration: Release
platform: Any CPU
clone_depth: 1
clone_folder: C:\consul
init:
- if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)
environment:
  CONSUL_VERSION: 0.6.4
  CLI_VERSION: Latest
install:
- cinst: 7zip.commandline
- ps: mkdir -Force c:\consul_install | Out-Null
- ps: |-
    $consul_zip = "consul_$($env:CONSUL_VERSION)_windows_386.zip"
    $consul_url = "https://releases.hashicorp.com/consul/$($env:CONSUL_VERSION)/$consul_zip"
    write-output "Downloading $consul_url"
    if (!(test-path "c:\consul_install\$consul_zip")) {Invoke-WebRequest $consul_url -OutFile "c:\consul_install\$consul_zip"}
    7z x -y c:\consul_install\$consul_zip -oc:\consul\consul.test
#- ps: mkdir -Force "C:\consul\scripts\obtain\" | Out-Null
#- ps: Invoke-WebRequest "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile "C:\consul\scripts\obtain\install.ps1"
#- ps: $env:DOTNET_INSTALL_DIR = "C:\dotnetcli"
#- ps: '& C:\consul\scripts\obtain\install.ps1 -Channel "preview" -version "$env:CLI_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
## add dotnet to PATH
#- ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- C:\consul_install -> appveyor.yml
nuget:
  disable_publish_on_pr: true
before_build:
- dotnet --info
- dotnet restore
build_script:
- dotnet --verbose build
- dotnet --verbose pack Consul --configuration Release
#build:
#  publish_nuget: true
#  publish_nuget_symbols: true
#  verbosity: minimal
before_test:
- ps: >-
    $consulJob = Start-Job {C:\consul\Consul.Test\consul.exe agent -dev -config-file C:\consul\Consul.Test\test_config.json}

    $running = $false

    do {
      Receive-Job -Job $consulJob
      if ($running -and $consulJob.State -ne "Running") {break}
      if ($consulJob.State -eq "Running") {
        $running = $true
        try {$result = convertfrom-json (invoke-webrequest -UseBasicParsing -TimeoutSec 1 -Uri http://localhost:8500/v1/status/leader).Content; sleep 1} catch {write-output "Waiting for Consul to come up..."}
      }
    } until (![string]::IsNullOrEmpty($result))

    Receive-Job $consulJob
test_script:
- dotnet test Consul.Test
after_test:
- ps: >-
    Get-Job | Stop-Job

    Get-Job | Receive-Job
deploy:
- provider: NuGet
  api_key:
    secure: dv44i0f5BvM3LZRUU/B0emsLEIbO9geASxNnMd074SXPligvsk81P8nzY/3m2z/z
  on:
    APPVEYOR_REPO_TAG: true
